spring:
  application:
    name: ead-payment-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: admin
      password: 'admin'