server:
  port: 8083
  servlet:
    context-path: '/ead-course-service/'

spring:
    application:
      name: ead-course-service
    datasource:
      url: jdbc:postgresql://localhost:5432/ead-course
      username: postgres
      password: admin
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true

    output:
      ansi:
        enabled: always

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://localhost:8082/ead-auth-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
