server:
  port: 8083
  servlet:
    context-path: '/ead-course-service/'

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/ead-course
      username: postgres
      password: admin
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true