server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: ead-auth-service
            uri: http://localhost:8082/
            predicates:
              - Path=/ead-auth-service/**
          - id: ead-course-service
            uri: http://localhost:8083/
            predicates:
              - Path=/ead-course-service/**