server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yramonn/ead-config-server-repo
          username: yramonn
#          password: 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


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

